### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tjulises** [Boettner-eric/Homepage#3]
Hello @Boettner-eric 

Nice project you have going on!
I'd like to contribute delivering a new logo!
What do you think?
A simple clean logo that suits with this awesome project!!
let me know, thanks!!!

**Comment by cohnmartha** [comment]
Yes ! I am definitely interested and If you are looking for more work I was also starting to design specific logos for the themes (discord, vim, gogh, light, dark, neon and soft).  I was thinking of changing the moon Icon to reflect the current theme.

**Comment by Boettner-eric** [comment]
Yes I am definitely interested.  I was planning on creating icons for my separate themes (discord, vim, soft, dark, gogh, light) to be displayed instead of the little moon icon.  I'd love to see any potential designs

**Comment by tjulises** [comment]
@Boettner-eric

**Comment by tjulises** [comment]
What happened? @Boettner-eric

**Comment by Boettner-eric** [comment]
Hello,
Sorry I've been away from GitHub for a little while.  This project is mostly about creating a usable homepage with keyboard only usage as a priority.  For a logo I was thinking something that reflects the tile based nature of the website or the keyboard navigation.  And finally for the license, I have updated the repo to include a .license file.
